# Generated by Django 3.2.4 on 2021-08-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20210813_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedmap',
            name='signRequirement',
            field=models.TextField(default='True'),
        ),
    ]
