# Generated by Django 3.2.4 on 2021-08-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_mapgeometry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapgeometry',
            old_name='item',
            new_name='mapItem',
        ),
    ]
