# Generated by Django 3.2.4 on 2021-08-07 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_item_mapgeometry_mapitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapGeometry',
        ),
    ]
