# Generated by Django 3.2.4 on 2021-08-07 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0004_delete_mapgeometry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapGeometry',
            fields=[
                ('auto_inc', models.AutoField(primary_key=True, serialize=False)),
                ('mapItem', models.TextField()),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
