# Generated by Django 3.2.4 on 2021-08-08 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0008_remove_completedmaps_layer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalMaps',
            fields=[
                ('auto_inc', models.AutoField(primary_key=True, serialize=False)),
                ('mapItem', models.TextField()),
                ('layerURL', models.TextField(default='https://services3.arcgis.com/nTlnK5Q4GIhY3A7b/arcgis/rest/services/docusign_hackathon/FeatureServer/0')),
                ('dateSubmitted', models.DateTimeField(auto_now_add=True)),
                ('gisUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
