# Generated by Django 3.2.4 on 2021-08-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_alter_completedmaps_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedmaps',
            name='status',
            field=models.TextField(),
        ),
    ]
