# Generated by Django 3.2.4 on 2021-08-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_alter_completedmaps_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedmaps',
            name='layer',
            field=models.TextField(default='https://services3.arcgis.com/nTlnK5Q4GIhY3A7b/arcgis/rest/services/docusign_hackathon/FeatureServer/0'),
        ),
        migrations.AlterField(
            model_name='mapgeometry',
            name='layer',
            field=models.TextField(default='https://services3.arcgis.com/nTlnK5Q4GIhY3A7b/arcgis/rest/services/docusign_hackathon/FeatureServer/0'),
        ),
    ]
