# Generated by Django 3.2.4 on 2021-08-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_auto_20210808_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapgeometry',
            name='reviewer',
            field=models.TextField(),
        ),
    ]
