# Generated by Django 3.2.4 on 2021-08-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_approvedmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapgeometry',
            name='comments',
            field=models.TextField(default='Enter your comments here'),
        ),
    ]
