# Generated by Django 3.2.4 on 2021-08-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0018_mapgeometry_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedmaps',
            name='comments',
            field=models.TextField(default='Enter your comments here'),
        ),
    ]
