# Generated by Django 3.2.4 on 2021-08-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_completedmaps_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalmaps',
            name='reviewerReadable',
            field=models.TextField(default='False'),
        ),
    ]
