# Generated by Django 3.2.4 on 2021-08-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0020_finalmaps_reviewerreadable'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalmaps',
            name='approvedBy',
            field=models.TextField(default='[]'),
        ),
    ]
