# Generated by Django 3.2.4 on 2021-08-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0021_finalmaps_approvedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalmaps',
            name='approvedBy',
            field=models.TextField(default='{}'),
        ),
    ]
